### ISSUE TITLE
用不了了

### ISSUE THREAD

**Issue by minguotan** [ganlvtech/bash-lets-encrypt#1]
Verifying www.zhuyu.xyz...
Traceback (most recent call last):
  File "runtime/acme_tiny.py", line 199, in <module>
    main(sys.argv[1:])
  File "runtime/acme_tiny.py", line 195, in main
    signed_crt = get_crt(args.account_key, args.csr, args.acme_dir, log=LOGGER, CA=args.ca, disable_check=args.disable_check, directory_url=args.directory_url, contact=args.contact, check_port=args.check_port)
  File "runtime/acme_tiny.py", line 147, in get_crt
    raise ValueError("Wrote file to {0}, but couldn't download {1}: {2}".format(wellknown_path, wellknown_url, e))
ValueError: Wrote file to runtime/challenges/9qLF1VvgmikghYROMX7O10E9Os34R3pUg7R6OYCjF80, but couldn't download http://www.zhuyu.xyz/.well-known/acme-challenge/9qLF1VvgmikghYROMX7O10E9Os34R3pUg7R6OYCjF80: Error:
Url: http://www.zhuyu.xyz/.well-known/acme-challenge/9qLF1VvgmikghYROMX7O10E9Os34R3pUg7R6OYCjF80
Data: None
Response Code: None
Response: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>

**Comment by ganlvtech** [comment]
请不要用我这个脚本了。
推荐使用 https://github.com/acmesh-official/acme.sh

**Comment by ganlvtech** [comment]
Wrote file to ..., but couldn't download ...
一般是因为你的网页服务器没有启动，或者根目录设置的不对，或者你的域名没有解析到此台机器。

**Comment by minguotan** [comment]
> Wrote file to ..., but couldn't download ...
> 一般是因为你的网页服务器没有启动，或者根目录设置的不对，或者你的域名没有解析到此台机器。

非常感谢提醒！

确实是nginx下的需要验证的配置路径有些问题，我根据这个后来调整了一下就好了，感谢！
